### ISSUE TITLE
(URGENT) Parse failure: Unable to parse "NIST Monograph 125"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#40]
The same goes for when the series name is not an abbreviation.

```
$ bundle exec nist-pubid convert "NIST Monograph 125"
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
bundler: failed to load command: nist-pubid (/Users/me/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bin/nist-pubid)
/Users/me/src/mn/nist-pubid/lib/nist_pubid/document.rb:144:in `parse': failed to parse serie for NIST Monograph 125 (NistPubid::Errors::ParseError)
	from /Users/me/src/mn/nist-pubid/exe/nist-pubid:44:in `convert'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
	from /Users/me/src/mn/nist-pubid/exe/nist-pubid:52:in `<top (required)>'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bin/nist-pubid:25:in `load'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bin/nist-pubid:25:in `<top (required)>'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `load'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/3.1.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/3.1.0/bundler/cli/exec.rb:23:in `run'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/3.1.0/bundler/cli.rb:484:in `exec'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/3.1.0/bundler/cli.rb:31:in `dispatch'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/3.1.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/3.1.0/bundler/cli.rb:25:in `start'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.3/libexec/bundle:48:in `block in <top (required)>'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/3.1.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/bundler-2.3.3/libexec/bundle:36:in `<top (required)>'
	from /Users/me/.rbenv/versions/3.1.0/bin/bundle:25:in `load'
	from /Users/me/.rbenv/versions/3.1.0/bin/bundle:25:in `<main>'
```

**Comment by mico** [comment]
Should we parse long document identifiers?
example:
`$ bundle exec nist-pubid convert "National Institute of Standards and Technology Special Publication 800-53, Revision 5"`
or only long series part?
example: 
`$ bundle exec nist-pubid convert "NIST Special Publication 800-53r5"`

**Comment by ronaldtse** [comment]
@mico yes that would be great, we wish to parse all 4 styles of document identifiers (legacy ID to PubID)

**Comment by mico** [comment]
So we want to parse both:
"NIST Monograph 125" and "National Institute of Standards and Technology Monograph 125", right?

**Comment by ronaldtse** [comment]
Yes.

**Comment by mico** [comment]
Now fully implemented abbreviated and long PubID for publisher, series, edition, revision and update.
Still need to implement:
- part
- version
- addendum
- section
- appendix
- errata
- index
- insert
- supplement
- stage
- translation

Could be quite a big task, so maybe postpone this for later. Could we do this together with refactoring?

**Comment by ronaldtse** [comment]
> Could be quite a big task, so maybe postpone this for later. Could we do this together with refactoring?

Good idea. Once we have the refactoring done, we can easily implement other PubID schemes.
