### ISSUE TITLE
(URGENT) Parse failure: "NIST GCR 17-917-45"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/nist-pubid#42]
```
| NIST | NISTGCR | Grant/Contract Reports | N/A | `NIST.GCR`
| https://nvlpubs.nist.gov/nistpubs/gcr/2017/NIST.GCR.17-917-45.pdf[NIST GCR 17-917-45]
```

```
me:~/src/mn/nist-pubid (main=): bundle exec nist-pubid convert "NIST GCR 17-917-45"
bundler: failed to load command: nist-pubid (/Users/me/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/bin/nist-pubid)
/Users/me/src/mn/nist-pubid/lib/nist_pubid/document.rb:144:in `parse': failed to parse serie for NIST GCR 17-917-45 (NistPubid::Errors::ParseError)
	from /Users/me/src/mn/nist-pubid/exe/nist-pubid:44:in `convert'
	from /Users/me/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
```

**Comment by mico** [comment]
Seems it's bug from https://github.com/metanorma/nist-pubid/blob/main/README.adoc

Looking at NIST Tech Pubs records:
```
 <publisher_item>
    <item_number item_number_type="report-number">NIST GCR 80-287</item_number>
 </publisher_item>
 <doi_data>
    <doi>10.6028/NBS.GCR.80-287</doi>
    <resource>https://nvlpubs.nist.gov/nistpubs/gcr/1980/gcr80-287.pdf</resource>
 </doi_data>

 <publisher_item>
    <item_number item_number_type="report-number">NIST GCR 01-820</item_number>
 </publisher_item>
 <doi_data>
    <doi>10.6028/NIST.GCR.01-820</doi>
    <resource>http://nvlpubs.nist.gov/nistpubs/gcr/2001/gcr01-820.pdf</resource>
 </doi_data>
```

Seems "NISTGCR" should be "NIST GCR".

**Comment by ronaldtse** [comment]
@mico I think so, should be "NIST GCR", as per https://github.com/metanorma/nist-pubid/pull/57#issuecomment-1008948753 :

> While the NIST GCR series is officially called "NISTGCR":
> 
> https://www.nist.gov/nist-pub-series/grantcontract-reports-nistgcr?page=1 <img alt="Screenshot 2022-01-10 at 10 52 38 PM" width="1136" src="https://user-images.githubusercontent.com/11865/148786080-d99eac52-c525-4853-aac7-43133998db46.png">
> 
> But most NIST GCR reports use the abbreviation of "NIST GCR", and this aligns with the change from "NISTIR" to "NIST IR".
